export const navigations = {
  home: 'Home',
  weddingGallery: 'Wedding Gallery',
  invitationGallery: 'Invitaion Gallery',
  eventsGallery: 'Events Gallery',
  aboutUs: 'About Us',
  // inquire: 'Inquire',
  // signIn: 'Sign In'
}

export const imagesCatalogue = {
  invitation1:'/images/Invitation/one.jpg',
  invitation2: '/images/Invitation/two.jpg',
  invitation3: '/images/Invitation/three.jpg',
  wedding1: '/images/Wedding/one.jpg',
  wedding2:'/images/Wedding/two.jpg',
  wedding3:'/images/Wedding/three.jpeg',
  wedding4: '/images/Wedding/four.jpg',
  wedding5:'/images/Wedding/five.jpeg',
  wedding6: '/images/Wedding/six.jpg',
  wedding7:'/images/Wedding/seven.jpg',
  wedding8:'/images/Wedding/eight.jpg',
  wedding9:'/images/Wedding/nine.jpg',
  wedding10:'/images/Wedding/ten.jpg',
  wedding11:'/images/Wedding/eleven.jpg',
  wedding12:'/images/Wedding/new.jpg',
  wedding13:'/images/Wedding/tanviandco2.jpg',
  wedding14:'/images/Wedding/service-Beauty-Services-Fashion-Designers.png',
  wedding15:'/images/Wedding/servicePhotography.png',
  wedding16:'/images/Wedding/service-Lightings.png',
  wedding17:'/images/Wedding/service-catering.png',
  wedding18:'/images/Wedding/service-DJ-Party.png',
  wedding19:'/images/Wedding/service-Music-Events.png',
  wedding20:'/images/Wedding/about_us.jpg',
}